### PR TITLE
Added "Getting Water to Your Homes" and "Dryville's First Water Works" section to the story #1

### PR DESCRIPTION
**Pull request by JananiKandsamy**
#1 This pull request adds the "Getting Water to Your Homes" and "Dryville's First Water Works" sections to the dryville_story.md file, enriching the story with additional details and completing the narrative of water supply challenges and solutions in Dryville.

### CODE REVIEW

**Review by abnerbog — CHANGES_REQUESTED** [review]
This is close ! The hyperlinks should point to the website in the [USGS article](https://www.usgs.gov/special-topics/water-science-school/science/story-water-dryville) instead of a local markdown (.md) file. For example, the text `at over 8 pounds a gallon` should point to [this hyperlink](https://www.usgs.gov/special-topics/water-science-school/science/water-density). There are a couple other hyperlinks to include in the `Getting Water to Your Homes` section.

**Comment by JananiKandsamy** [comment]
Thank you for the comment.

**Comment by JananiKandsamy** [comment]
I have updated the file as you have mentioned. Do need I to submit a new pull request?

**Review by abnerbog — APPROVED** [review]
You're all set to move on to the next step!

**Pull request merged**
